export default {
  STARTLE: 'STARTLE',
  STARTLE_ATTEMPT: 'STARTLE_ATTEMPT',
  STARTLE_SUCCESS: 'STARTLE_SUCCESS',
  STARTLE_FAILED: 'STARTLE_FAILED',
  STARTLE_RESET: 'STARTLE_RESET',
  SHOW_STARTLE_OPTIONS: 'SHOW_STARTLE_OPTIONS',
  HIDE_STARTLE_OPTIONS: 'HIDE_STARTLE_OPTIONS',
  CHOOSE_STARTLE_COUNT: 'CHOOSE_STARTLE_COUNT'
}
