export default {
  STARTLE: 'STARTLE',
  STARTLE_ATTEMPT: 'STARTLE_ATTEMPT',
  STARTLE_SUCCESS: 'STARTLE_SUCCESS',
  STARTLE_FAILED: 'STARTLE_FAILED',
  STARTLE_RESET: 'STARTLE_RESET',
  STARTLE_ANNOYED: 'STARTLE_ANNOYED',
  SHOW_STARTLE_OPTIONS: 'SHOW_STARTLE_OPTIONS',
  HIDE_STARTLE_OPTIONS: 'HIDE_STARTLE_OPTIONS',
  CHOOSE_STARTLE_COUNT: 'CHOOSE_STARTLE_COUNT',
  CONNECT_WALKIE_TALKIE: 'CONNECT_WALKIE_TALKIE',
  DISCONNECT_WALKIE_TALKIE: 'DISCONNECT_WALKIE_TALKIE',
  SEND_RECORDING: 'SEND_RECORDING',
  START_RECORDING: 'START_RECORDING',
  STOP_RECORDING: 'STOP_RECORDING',
  CLEAR_RECEIVED_AUDIO: 'CLEAR_RECEIVED_AUDIO',
  NEW_AUDIO_MESSAGE: 'NEW_AUDIO_MESSAGE'
}
