export default {
  STARTLE: 'STARTLE',
  STARTLE_ATTEMPT: 'STARTLE_ATTEMPT',
  STARTLE_SUCCESS: 'STARTLE_SUCCESS',
  STARTLE_FAILED: 'STARTLE_FAILED',
  STARTLE_RESET: 'STARTLE_RESET',
  STARTLE_ANNOYED: 'STARTLE_ANNOYED',
  SHOW_STARTLE_OPTIONS: 'SHOW_STARTLE_OPTIONS',
  HIDE_STARTLE_OPTIONS: 'HIDE_STARTLE_OPTIONS',
  CHOOSE_STARTLE_COUNT: 'CHOOSE_STARTLE_COUNT',
  SAVE_RECORDING: 'SAVE_RECORDING',
  SHOW_RECORDING_SAVED: 'SHOW_RECORDING_SAVED',
  HIDE_RECORDING_SAVED: 'HIDE_RECORDING_SAVED',
  NEW_AUDIO_MESSAGE: 'NEW_AUDIO_MESSAGE'
}
